repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        name: Check for files larger than 5 MB
        args: [ "--maxkb=5120" ]
      - id: end-of-file-fixer
        name: Check for a blank line at the end of scripts (auto-fixes)
      - id: check-yaml
      - id: trailing-whitespace
        name: Check for trailing whitespaces (autofixes)
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.2
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
    - id: nbstripout
      files: ".ipynb"
# - repo: https://github.com/Yelp/detect-secrets
#   rev: v1.0.3
#   hooks:
#     - id: detect-secrets
#       name: detect-secrets - Detect secrets in staged code
#       args: [ "--baseline", ".secrets.baseline" ]
#       exclude: .*/tests/.*
- repo: local
  hooks:
    - id: pyenv-unit-tests
      name: Pyenv Unit Tests
      entry: bash -c 'PYTHONPATH=$(pyenv prefix)/lib/python3.11.8/site-packages:$PYTHONPATH pytest tests/unit_tests/'
      language: system
      always_run: true
      pass_filenames: false
