steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx',
           'build',
           '--platform=linux/amd64',
           '-t',
           'europe-west2-docker.pkg.dev/govuk-ai-publishing/feedback-dashboard/app:latest',
           '-f',
           'Dockerfile',
           '.']

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'europe-west2-docker.pkg.dev/govuk-ai-publishing/feedback-dashboard/app:latest']

images:
  - europe-west2-docker.pkg.dev/govuk-ai-publishing/feedback-dashboard/app:latest
