version: '3.11'
services:
#   qdrant:
#     image: qdrant/qdrant
#     ports:
#       - "6333:6333" # Expose the default Qdrant port
#     volumes:
#       - qdrant_data:/data # Persist Qdrant data

#   init_script:
#     build:
#       context: .
#       dockerfile: ./collection/Containerfile
#     depends_on:
#       - qdrant
#     environment:
#       - QDRANT_HOST=qdrant

  streamlit_app:
    build:
      context: .
      dockerfile: ./app/Containerfile
    ports:
      - "8501:8501" # Expose the default Streamlit port
    # environment:
    #   - QDRANT_HOST=qdrant # Use the service name as the hostname for inter-service communication
    # depends_on:
    #   - qdrant

volumes:
  qdrant_data:
