# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install -e .

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Define environment variable
# Use to specify the command-line options you want to start Streamlit with
ENV STREAMLIT_SERVER_PORT 8501

# Run main.py when the container launches
CMD ["streamlit", "run", "app/main.py"]
