# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the python script into the container at /app
COPY . /app

# Install Python dependencies (if any)
# If you have dependencies, make sure to copy and install them as well
COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install -e .

# Command to run the script
# This might need to wait for Qdrant to be fully ready
CMD ["python", "collection/create_collection.py"]
