# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Install Poetry
RUN pip install poetry

# Copy the python script and configuration files into the container at /app
COPY . /app
COPY docker-compose.env /app

# Copy Poetry configuration files
COPY pyproject.toml poetry.lock* /app/

# Install Python dependencies using Poetry
# Note: Using `--no-root` to not install the project package yet
RUN poetry config virtualenvs.create false && \
    poetry install --no-dev --no-interaction --no-ansi --no-root

# Now install the project package, in editable mode if needed
RUN poetry run pip install -e .

# Command to run the script
# This might need to wait for Qdrant to be fully ready
CMD ["python", "collection/create_collection.py"]
