keys_to_extract = [
    "feedback_record_id",
    "created",
    "score",
    "feedback",
    "url",
    "page_title",
    "department",
    "primary_department",
    "document_type",
    "feedback_type",
    "urgency",
    "taxons",
    "publishing_app",
    "locale",
    "sentiment",
    "spam_classification",
]
